---
# Take action upon a true statement
- hosts: localhost
  tasks:
    - command: hostname -s
      when: ansible_distribution == "CentOS"
      register: hostname_reg

    - name: Install package
      yum: 
        name: httpd
        state: present
      when: hostname_reg.changed


...
