---
# Loop with_items using when

- hosts: localhost
  tasks:
    - name: Create user
      file:
        path: /tmp/{{ item }}
        state: touch
      with_items: 
        - new-01
        - new-02


...
