---
# Odd and Ebem
- hosts: localhost
  tasks:
    - name: Odd and Even
      debug:
        msg: >-
             {% for value in range(1,10) -%}
                  {% if value is even -%}
                     {{ value }}
                  {% endif %}
             {% endfor %}
...
